### ISSUE TITLE
Can't add testnet drip list to testnet drip list

### ISSUE THREAD

**Issue by jo-elimu** [drips-network/app#1004]
https://deploy-preview-997--drips-app-v2.netlify.app/app/drip-lists

![](https://github.com/drips-network/app/assets/1451036/7f929b6f-91a3-429c-bedd-bbfd7e5c64f9)

**Comment by jo-elimu** [comment]
I had to replace `deploy-preview-997--drips-app-v2.netlify.app` with `drips.network` to make it work.

https://deploy-preview-997--drips-app-v2.netlify.app/app/drip-lists/27858410146581548959600601401034926424750391509495451346687702673937

**Comment by evvvritt** [comment]
Thanks but this is expected with our API. Perhaps if this issue persists on our production testnet site [goerli.drips.network](https://goerli.drips.network), you can reopen
