### ISSUE TITLE
Funds page not loading when opened as Safe{Wallet} app

### ISSUE THREAD

**Issue by jo-elimu** [drips-network/app#1054]
https://app.safe.global/apps

![](https://github.com/drips-network/app/assets/1451036/9ae3a8ec-50d1-4553-ba14-11ec72b03e12)

**Comment by lovelymahor** [comment]
I want to solve this issue please assign it to me

**Comment by efstajas** [comment]
hey @jo-elimu do you still see this issue today?

**Comment by efstajas** [comment]
Hey all, this should be fixed. Let me know if it happens again.
