### ISSUE TITLE
Remove dates from blog

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1058]
Since we are not posting on the blog as often as we thought we would, we should remove the post dates. I always prefer to remove the post dates since it can look out of date very fast, and removing the dates removes the thought from people's minds, so less stress to post so often.

**Comment by efstajas** [comment]
Not sure if this is a good idea when we make announcements like a new founder being onboarded or comitting some amount. The date is just an important detail to know about the announcement
