### ISSUE TITLE
mouse middle click should only open in new tab

### ISSUE THREAD

**Issue by o-az** [drips-network/app#1101]
Reporting this unexpected behavior:

currently in on any site when I use the middle mouse button it opens the link in a new tab. In https://www.drips.network/app/projects/all however it both opens in new tab and opens in current tab.

demo:

https://github.com/drips-network/app/assets/23618431/4b8452e8-a260-4a28-a41e-62d3f6483e77

**Comment by brandonhaslegs** [comment]
I'm not familiar with the middle click. Maybe @efstajas or @jtourkos would know more about this.
