### ISSUE TITLE
Populate maintainer & dependency splits for projects from CSV

### ISSUE THREAD

**Issue by nya-elimu** [drips-network/app#1102]
Once per month we are manually copying and pasting Ethereum addresses and impact percentages from a [`FUNDING_SPLITS.csv`](https://github.com/elimu-ai/web3-wiki/blob/main/funding-splits-content/github_webapp/FUNDING_SPLITS.csv) file into the maintainer list at https://www.drips.network/app/projects/github/elimu-ai/webapp:

```csv
ethereum_address,github_username,impact_percentage
0x5D388Ec24Cc2C0C77458338696aa63AFB706A7b1,nya-elimu,51.02
0xd46Cc93E3eE6a4fb532D9B48E95be7eD8f8f1DA0,jo-elimu,38.77
0x3965d420cde24fe00f742cb31257ca90e04556a7,tomaszsmy,1.20
0x819e4F5E912abb36c8f6c03790e7508e03cc37a3,UmenR,1.12
0x5367a6d4F5991327Bb20466684790e394bE000dE,Shubham-Vishwakarma,0.76
0x0000000000000000000000000000000000000000,aschworer,0.73
0x6321286F9B73f427C72e1f9F1bC6b3d25eF06605,hhio618,0.57
0x0000000000000000000000000000000000000000,urosht,0.57
0x4709ebf314c6492d57f4c6d4f57357d5b2bb074e,vrudas,0.56
0x914dBEe36BcAb63B2D15fAED08839Be43797b421,watr-sheep,0.38
```
<p align="center">
⬇️
</p>

![](https://github.com/drips-network/app/assets/15718174/f88b80fa-db4e-4a43-928e-6b288c9e0344)

It would be a great time-saver to be able to import the maintainer list data directly from a CSV file for all of our GitHub repos.

**Comment by nya-elimu** [comment]
@brandonhaslegs

**Comment by brandonhaslegs** [comment]
@nya-elimu can you test this out and see if it works for you?

**Comment by efstajas** [comment]
Apologies, closed this accidentally. We launched CSV import for new Drip Lists for now, not yet for maintainers.

**Comment by nya-elimu** [comment]
> We launched CSV import for new Drip Lists for now, not yet for maintainers.

Thank you, @efstajas. Would it be possible to add the CSV import feature to _existing_ Drip Lists as well?

<kbd>![](https://github.com/user-attachments/assets/e51de461-c59a-4968-b4f4-3aea9ab0d5b7)</kbd>

We are maintaining Drip Lists with 50-100 recipients that get adjusted monthly, and it's painful to update these manually. So for us (in the long-term) the CSV import feature would actually be more useful for _existing_ Drip Lists than for _new_ Drip Lists.

**Comment by efstajas** [comment]
The above ⤴ is live, but still can't upload a CSV for setting maintainers / dependencies of projects.
