### ISSUE TITLE
Allow importing splits from CSV

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#1143]
When populating Drip List or Project splits, it should be possible to import splits from a CSV.

CSV format:

```
account,percentage
0x79756b6C2f913271fc0ee29A877fbd98258972BF,33.3334
https://github.com/wevm/wagmi,33.3333
https://www.drips.network/app/drip-lists/31017209032870028068280040871339261037749177808773684797297972107972,33.3333
```

if there is no percentage (e.g. setting collaborators on a collab. drip list):

```
account
0x79756b6C2f913271fc0ee29A877fbd98258972BF
...
```

**Comment by efstajas** [comment]
**Considerations**

- Import can be initiated from anywhere the List Editor component is used (Drip List creation, setting maintainer or dependency splits on projects, etc.)
- after you click import, needs to show the expected format and give you a d&d target + file selector (same as when uploading custom avatar)
- if you click import after already setting splits manually, warn user about changes being overwritten
- errors
  - completely wrong format / not a valid CSV
  - per-line errors (e.g. project not found, invalid URL etc.): after import process, show errors per line, allow user to either try again or proceed (with the errored lines missing)
  - percentages don't add up: just drop user into the editor, which will then be in an error state and force user to fix it either manually or by changing the CSV and re-importing

**Comment by brandonhaslegs** [comment]
Design coming along here https://www.figma.com/design/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?node-id=10036-25650&t=xuFCcHkQrTzgo7fv-1

**Comment by nya-elimu** [comment]
@efstajas As it relates, also see #1102

Here is an example of a CSV file we want to import data from: https://github.com/elimu-ai/web3-wiki/blob/main/funding-splits/content/FUNDING_SPLITS_HIN.csv (for https://www.drips.network/app/drip-lists/44233954899343831995062217275215737681377860849646413826815741964160)

(We update these files once per month, before manually copying the data into our Drip Lists, which is a tedious task.)

**Comment by nya-elimu** [comment]
> Design coming along here https://www.figma.com/design/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?node-id=10036-25650&t=xuFCcHkQrTzgo7fv-1

@brandonhaslegs The "↓ Import from CSV" option is missing from the "Edit your Drip List" view:

![](https://github.com/user-attachments/assets/07f99736-467b-49af-841b-dd76bff2d4c8)

**Comment by efstajas** [comment]
> @nya-elimu This is great to know! I think if you switch `contributor ID` and `impact percentage` your CSV import for what we're building will work. We will sipmly ignore `contributor ID` (as long as it comes after address and percentage). @efstajas correct me if I'm wrong 😄 

Ideally our implementation would just look for the expected column names (presumably account & percentage), and ignore all others — then the order of the columns wouldn't matter.

**Comment by nya-elimu** [comment]
> Ideally our implementation would just look for the expected column names (presumably account & percentage), and ignore all others — then the order of the columns wouldn't matter.

@efstajas Did some testing of the new "Import from CSV" feature, and the column name matching doesn't seem to work for us:

## 1. Create a Drip List:

<kbd>![](https://github.com/user-attachments/assets/3cae87f6-fd19-47d2-8aa1-35a9ce28b884)</kbd>

## 2. Prepare CSV file with `recipient` and `percentage` as column names:

<kbd>![](https://github.com/user-attachments/assets/8ca131ac-e656-4a14-9735-3c0e4c961c3e)</kbd>

## 3. Upload the CSV file:

[`FUNDING_SPLITS_HIN.csv`](https://github.com/user-attachments/files/16536844/FUNDING_SPLITS_HIN.csv)

```csv
recipient,contributor_id,percentage
0x0fa31ed0fa8e2d2a958b5b5d3c9e9b565abe3e93,1,58.50
0x754a9162678eaae9b8949eebd85ed1936b5abce3,2,24.30
0xec35e628dbf08ae096addb187a485e01d39e7560,3,10.20
0xda0bc9ecd14d0346ee41085edbc46a950bebd73d,4,4.0
0x2fab1fa377cb2631f0bb002fbcd0178819cd33ac,5,3.0
```

## 4. The `percentage` column is not imported correctly:

<kbd>![](https://github.com/user-attachments/assets/10326620-f044-4c51-a9ec-1fe95dd18139)</kbd>

**Comment by efstajas** [comment]
Hey @nya-elimu, thanks a lot for giving this a try. You're right, that part didn't make it in the implementation. It expects the format to 100% match the provided example (only two columns, second with percentage).
