### ISSUE TITLE
Error responses occasionally being cached by `cached` utility

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#1206]
We use `cached` to fetch data either from cache or source of truth. There is currently no mechanism that prevents it from caching error responses returned by fetch functions that don't throw. This may result in error responses being cached, which then breaks the app until the cache key in question expires.

We need to ensure:
- Ideally, fetch functions passed to `cached` thoroughly validate the data they return
- All fetch functions must throw if an error is encountered, even if said error is only visible by examining the response (e.g. checking `Response.ok` key)
- `cached` must throw if the fetch function does, and not persist anything on Redis

**Comment by mhgbrown** [comment]
Do you remember which sort of cached error response was causing trouble? After some sleuthing, there's 5 instances of the use of `cached`....

[One use is for the `cachedTotalDrippedPrices`](https://github.com/drips-network/app/blob/6dcea711ecdcadce7964ce587d3db989340ec0a4/src/lib/utils/total-dripped-approx.ts#L111), which eventually calls `getCmcPrices`, which does not throw, but returns an empty object if there is an error. That could be bad if we want to try fetching prices before 6 hours. On the other hand, this is kind of a nice accidental backoff mechanism if some underlying API is borked.

Another use is `fetchDripsProject`, which uses `query from '$lib/graphql/dripsQL';`, which may not throw an error for certain GraphQL conditions. What I'm curious about is that [this usage](https://github.com/drips-network/app/blob/6dcea711ecdcadce7964ce587d3db989340ec0a4/src/routes/(pages)/app/(app)/projects/(forges)/github/%5BgithubUsername%5D/%5BgithubRepoName%5D/%2Bpage.server.ts#L40) does not return anything inside of the `cached` fetcher block, so `undefined` is getting cached?

[Similarly, another use is `github.getRepoByUrl`](https://github.com/drips-network/app/blob/6dcea711ecdcadce7964ce587d3db989340ec0a4/src/routes/api/github/%5BrepoUrl%5D/%2Bserver.ts#L36), which uses the Octokit library, which does throw in the case of a bad fetch.

[Then there's this use](https://github.com/drips-network/app/blob/6dcea711ecdcadce7964ce587d3db989340ec0a4/src/routes/api/fiat-estimates/id-map/%2Bserver.ts#L31) in the id-map api endpoint, which is susceptible to caching a bad response. That's pretty straightforward to address.

Finally, there's [this use when loading the default explore page data](https://github.com/drips-network/app/blob/6dcea711ecdcadce7964ce587d3db989340ec0a4/src/routes/(pages)/app/(app)/components/load-default-explore-page-data.ts#L108). Here it appears that fetching the blog posts or fetching the tlv could fail and the responses be cached if they're parsable as json...
