### ISSUE TITLE
Add custom share modal

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1238]
Copy isn't final!

`••• More` opens the system share diaglog.

Also this is only for desktop, for mobile, open the system share sheet.

![image](https://github.com/user-attachments/assets/ed4eecba-0004-47a4-991e-daa1b21a9d4b)

**Comment by efstajas** [comment]
If the web share API is available AND it's a touchscreen device, default to system share

ALL other cases, use custom share sheets

**Comment by mhgbrown** [comment]
Every route does have a share image now, but only some have special route-specific ones. All others fall back to the [default share image](https://drips.network/assets/share/og-generic.png).

The custom share modal logic should apply everywhere `share-button.svelte` is used.

I would say that `share-button.svelte` should accept an optional `downloadableImageUrl` prop, and only show the downloadable image on the custom share modal if that prop is defined.

That prop should then be set to the custom share images on routes that have one, which right now are:
- project profiles
- drip lists
- blog posts

To figure out the paths those dynamic images you can check the values passed to `<HeadMeta>` on the respective routes, e.g. [here](https://github.com/radicle-dev/drips-app-v2/blob/c045d0ba51900965871214327cd65e91dd79cd27/src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte#L251)
