### ISSUE TITLE
Add check and elevation to selected color

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1246]
The selected color should have a check icon and an elevation shadow on it

Currently:
<img width="647" alt="Arc 2024-10-07 16 39 01" src="https://github.com/user-attachments/assets/85c107f0-2b60-449a-9b38-5f866a7a9a85">

Should look like this tho
<img width="671" alt="image" src="https://github.com/user-attachments/assets/f90e9abf-4794-4f8a-b53a-39712aa89f65">

**Comment by efstajas** [comment]
#803
