### ISSUE TITLE
Fake progress bar on transaction screen

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1249]
FVM tends to be a bit slow, so we want to display some progress on the Transaction screen during the project claim flow. There should be a "fake" progress bar that assumes a reasonable duration and resolves fully once the underlying task is complete.

There should be a progress bar displayed in the project claim flow while:
- We're waiting for the project owner update from the Oracle
- We're waiting for the final claim TX being confirmed on-chain

**Comment by efstajas** [comment]
Designs: https://www.figma.com/design/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?node-id=11720-202409&t=3uHO5wdS7wiWJZUj-1
