### ISSUE TITLE
Loading forever on Initial top-up step

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1254]
The spinner just spins forever and the continue button is disabled.

![image](https://github.com/user-attachments/assets/de1ce14d-7ac0-4545-a2ba-d31a9b17bfcf)

**Comment by efstajas** [comment]
@brandonhaslegs when this happened, did you have WFIL in your wallet or not?

**Comment by brandonhaslegs** [comment]
No I didnt

**Comment by efstajas** [comment]
<img width="787" alt="Screenshot 2024-10-18 at 15 10 23" src="https://github.com/user-attachments/assets/5f19f29b-29be-478a-85a8-1121e3dd5d0f">

Can't repro this ATM... still happening for you?

**Comment by brandonhaslegs** [comment]
Yep same for me
