### ISSUE TITLE
Improve filename of downloaded share image

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1292]
This should be just the name of the project or Drip List instead of all these %

`https%3A%2F%2Fgithub.com%2Fdethcrypto%2FTypeChain.png`

So for projects:  `dethcrypto / TypeChain.png`

And for Drip Lists: `Octant Dependencies.png`

**Comment by mhgbrown** [comment]
With the Arc browser, the downloaded image for https://www.drips.network/app/projects/github/dethcrypto/TypeChain is named (very decently!) "Typechain from dethcrypto.png".

**Comment by brandonhaslegs** [comment]
yeah I use Arc (but have that feature turned off so it actually doesn't do it with that feature off)

**Comment by mhgbrown** [comment]
Ah, Arc is doing funny business with AI!
