### ISSUE TITLE
Add a warning not to send funds to exchange-managed addresses

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#1295]
When entering project maintainers and dependencies, we should display a warning not to enter any exchange-managed addresses, because funds sent there will not be accessible.

**Comment by brandonhaslegs** [comment]
If we can detect it, just a standard error will work fine

![Image](https://github.com/user-attachments/assets/a0f7fc45-1785-481f-a7f6-1e58cfcec857)

**Comment by efstajas** [comment]
we can't (reliably and at scale) detect it, so it'll have to be there always unfortunately

**Comment by brandonhaslegs** [comment]
How bout this ![Image](https://github.com/user-attachments/assets/6980149a-81a4-4f5d-9e6b-b7ba375aff91)

**Comment by brandonhaslegs** [comment]
Also maybe the list could be disabled until the user presses "I understand"

![Image](https://github.com/user-attachments/assets/f54b691e-cadf-4ead-b370-a04cb06a7666)

**Comment by brandonhaslegs** [comment]
Comment test to see if it closes the issue.

**Comment by efstajas** [comment]
@efstajas think about final copy

**Comment by mhgbrown** [comment]
Are we just adding the notice in this particular spot or should it also appear, for example, when creating a Drip List?
