### ISSUE TITLE
Profile and ENS names not loading

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1302]
Looks like the ENS metadata is there but the profile pic and name are gone in the whole app for every profile.

![Image](https://github.com/user-attachments/assets/7a478407-5639-49fb-a2ac-5264682463a7)
![Image](https://github.com/user-attachments/assets/ace83061-42c8-4c86-9430-46a08a93c8c0)

**Comment by efstajas** [comment]
Seems like for some profiles it works, e.g. drips.network/efstajas.eth (it actually loads the image & name, but the image link is just broken for my ens name)

Need to investigate this, really weird.
