### ISSUE TITLE
Add embeddable support button to share dialog

### ISSUE THREAD

**Issue by mhgbrown** [drips-network/app#1359]
People who either don't have access to or just didn't connect their wallet may be interested in embedding a Support button on their project's README, but currently don't have a way to launch the configurator.

We should add "Embed support button" as one of the share targets in the Share dialog for projects.

When clicked, it should trigger a `sidestep` into the share button configurator, which should have a `Back` button for going back to the Share dialog.

**Comment by efstajas** [comment]
IMO icon for this could just be the "Settings" icon again, since it launches the configurator. @brandonhaslegs wdyt?

**Comment by efstajas** [comment]
@brandonhaslegs to include tweak for share design so we don't end up with unbalanced columns

**Comment by brandonhaslegs** [comment]
So like this

![Image](https://github.com/user-attachments/assets/0bf35095-5a8c-47f7-8607-92a92a9f910d)
