### ISSUE TITLE
style: allow overriding border-color

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#152]
In my opinion, the new style borders are a bit too loud (particularly dark theme). Since we can't make less than 1px, I propose dimming them, or at least having control to do so:

1. add CSS var `--theme-border-color: var(--color-foreground)` to whichever design system repo we're importing
2. apply to all borders + box-shadows in the design system

Then, in app we can override to dim:

```
:root {
  --theme-border-color: var(--color-foreground-level-6);
}
[dark-theme] {
  ...
}
```

other attributes we should do this for? `border-radius`?
@brandonhaslegs @efstajas

**Comment by brandonhaslegs** [comment]
We could still do this with theming. Maybe at some point we make a normie theme.
