### ISSUE TITLE
Enhancement - Bundle transactions such that any collectable funds can be used immediately in a stream

### ISSUE THREAD

**Issue by bordumb** [drips-network/app#164]
## Problem

Let's assume someone has "collectable" funds in their incoming balance.

In order to "Create stream" they must do this:
1. "Collect" incoming funds
2. "+Add" to outgoing balance
3. Then they can "Create stream"

This UX feels a bit clunky.

## Proposal

Ideally, if someone has "collectable" funds, the front-end would seamless let the user go directly to "Create stream" and pull from the "collectable" funds balance. 

If it requires for these funds to be "+Add"ed to the outgoing balance, it would be good to abstract this step and bundle those transactions behind the scenes, perhaps adding a small message about how this works/why gas fees may be slightly higher if this is what's going on.

**Comment by efstajas** [comment]
This is definitely a good idea 👍

So far in the designs, we intend for a flow that allows collecting & adds funds in one transaction, which would be pretty close to what you're describing.

We should look into connecting this directly with creating a new stream as you describe too, but I'd argue that a separate flow for collect + top up is the lower-hanging fruit, given this is also useful for topping up already-existing streams.

Either way, let's use this issue to track that!

**Comment by bordumb** [comment]
> I'd argue that a separate flow for collect + top up is the more important first step

Agreed.

My mental model of how this could work (with probably broken pseudo code) is like:
```python
collectable_funds = {
    'eth': 5,
    'rad': 10
}

balance_funds = {
    'eth': 100,
    'rad': 10000
}


def collect_funds(token_to_collect: str, amount_to_collect: float):
    pass

def add_funds_to_balance(token_to_collect: str, amount_to_collect: float):
    pass

def read_collectable_funds(collectable_funds: dict) -> dict:
    return collectable_funds

def read_balance_funds(balance_funds: dict) -> dict:
    return balance_funds


def direct_collect_and_add(token_to_collect_and_add: str, amount_to_collect_and_add: float):
    collectable_funds = read_collectable_funds()
    if collectable_funds is not None:
        collect_funds(token_to_collect=token_to_collect_and_add, amount_to_collect=amount_to_collect_and_add)
        add_funds_to_balance(token_to_add=token_to_collect_and_add, amount_to_add=amount_to_collect_and_add)
    else:
        print("You're broke as a joke")


def create_stream(token_to_stream: str, amount_to_stream: float):
    collectable_funds = read_collectable_funds()
    balance_funds = read_balance_funds()
    total_available_funds = {
        'collectable_funds': collectable_funds,
        'balance_funds': balance_funds
    }

    if collectable_funds is not None:
        direct_collect_and_add(token_to_collect_and_add=token_to_stream, amount_to_collect_and_add=amount_to_stream)
    else:
        print("You're broke as a joke")
```

```python
def
```

**Comment by brandonhaslegs** [comment]
related to #787

**Comment by efstajas** [comment]
Marking as not planned since it's not that relevant anymore with our new focus on dependency funding functionality.
