### ISSUE TITLE
Allow setting drips and updating balance in one transaction

### ISSUE THREAD

**Issue by CodeSandwich** [drips-network/app#168]
Currently topping up and updating the list of receivers are two very distinct steps generating two separate transactions. This slows down UX and wastes gas, in the worst case few-fold.

**Comment by efstajas** [comment]
I'm closing this as not planned for now:

- It's already possible to create a stream to a Drip List through the Continuous Donation modal, which already allows an immediate "initial top-up". So, this task would only affect the "Create stream" modal on the "Funds" page, which is increasingly irrelevant as we add "Support" buttons to all entities users may want to stream to (only one missing is an address profile).

If anyone feels strongly about this, please feel free to re-open with a comment ✌

**Comment by efstajas** [comment]
Apologies, I was mistaken, there's no way to make an initial top-up on the "Continuous Donation" modal. That's only possible when creating a continuous donation directly while creating a new Drip List. I will create a new task for overhauling the Continuous Donation modal with this & date pickers, and those changes will also apply to the Create Stream modal.

**Comment by efstajas** [comment]
#1299
