### ISSUE TITLE
Drips setup modal droplets animation is cut

### ISSUE THREAD

**Issue by CodeSandwich** [drips-network/app#177]
It's only cut on the bottom, some droplets are only partially visible, the top is fine. A very minor issue.

![image](https://user-images.githubusercontent.com/26183680/205291277-355773e9-8a7e-4087-af69-d37b73950b87.png)

**Comment by CodeSandwich** [comment]
Tested on Firefox and Chromium on desktop Linux, both act the same. I have some dual-screen-HiDPI-Wayland-fractional-scaling unresolved mess which kind of works but not quite. Running `window.devicePixelRatio;` in Firefox console yields `1.5` and on Chromium `2.0000000596046448`, but in the end both render things the same size on the screen.

**Comment by efstajas** [comment]
Haha fun, that's probably the reason then. The animation uses `window.devicePixelRatio` to determine scale: https://github.com/radicle-dev/drips-app-v2/blob/main/src/lib/components/drips-animation/drips-animation.svelte#L5

Unsure how to fix it, maybe it's too much of an edge case to bother…? I'll make sure it behaves properly on a broader range of devices though.

**Comment by efstajas** [comment]
Ah, actually the fact that it maxes out at `2` is probably the culprit, if the real ratio is uneven. Will fix.

**Comment by efstajas** [comment]
@CodeSandwich Closing for now assuming that it's been fixed since. Lmk if you still see this.
