### ISSUE TITLE
Comma instead of period

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#386]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/4406983/229127995-9a4de78d-0d30-4bf2-92a7-93c3d9dfd2c3.png">

This is only on the add funds modal, when you have "Max" selected

This should be a period.

And arguably if it's a round number it doesn't need any decimal at all.

**Comment by efstajas** [comment]
This is a system / browser setting.

**Comment by efstajas** [comment]
Hold on, it turns out that there appears to be a way to force a locale on a site and this apparently changes the way numbers are displayed on a site… do you think we should force periods always, or make it dependent on the user's locale settings across the board? 🤔

**Comment by evvvritt** [comment]
I would vote it should be locale but wdyt @brandonhaslegs?
the numbers are currently awkward on drip list as well (was considering making a new issue on it)
<img width="1532" alt="Screenshot 2023-09-06 at 13 57 17" src="https://github.com/drips-network/app/assets/6071219/7aefc4e5-8066-496d-b3c4-bb978ae4ddac">

**Comment by brandonhaslegs** [comment]
@evvvritt Yeah it should be based on the language.

But also I was trying to say it isn't consistent. In the screenshot there's `900.000000 USDC` and then `900,0 USDC`. Something isn't right.

The formatting of numbers generally needs work. 900,0 is an awkward formatting too.
