### ISSUE TITLE
Edit splits should go to the Splits setup modal

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#391]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/4406983/229115778-89255f1c-dadc-42f1-93b2-6c852e6bd709.png">
should go here:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/4406983/229115837-643c5183-05f3-498e-80e2-bdfaa45ff3d8.png">

**Comment by efstajas** [comment]
Closing since that card & address driver splits are no longer a thing
