### ISSUE TITLE
Make the sparkles an svg

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#427]
And they should have the primary color, instead of just being text emojis

<img width="69" alt="Screenshot 2023-04-19 at 22 19 33" src="https://user-images.githubusercontent.com/4406983/233206638-0b0dddb1-92a3-4888-96a8-d932ecd455b2.png">

**Comment by efstajas** [comment]
tbh, i don't think this matters at all 😬 feel free to reopen if you really feel strongly^^

**Comment by brandonhaslegs** [comment]
If we wanna do exactly it perfectly right. But yeah it doesn't matter.
