### ISSUE TITLE
Add more visible button to "Add json file to repo"

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#507]
<img width="744" alt="image" src="https://github.com/radicle-dev/drips-app-v2/assets/4406983/9a173b86-c585-4d3b-86b9-aaeca2c0816e">

Add primary button under the paragraph "Add this to my repo"

**Comment by brandonhaslegs** [comment]
Would be nice to link up this update with updating this modal to match all other modals

<img width="566" alt="image" src="https://github.com/drips-network/app/assets/4406983/2a79b222-7690-4482-bad8-82b0a6ad1620">

So just updating the header to look like this. 

But yeah the focus of this issue is just adding the single blue button "Add this to my repo" and removing the tiny ↗️ icon.

**Comment by evvvritt** [comment]
Hmm, feels odd to me it's above the code snippet?

**Comment by brandonhaslegs** [comment]
Yep, doink

<img width="527" alt="image" src="https://github.com/drips-network/app/assets/4406983/c083916a-e7cf-48f0-a361-ab118da2b993">
