### ISSUE TITLE
Pencil illustration is messed up

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#523]
The SVG is messed up
<img width="366" alt="image" src="https://github.com/drips-network/app/assets/4406983/f9724086-cd63-473b-9229-4fee222129f4">

**Comment by efstajas** [comment]
@brandonhaslegs i tried fixing but getting the same result every time with an export of the SVG. probably needs some flattening action in Figma.

**Comment by brandonhaslegs** [comment]
@efstajas wish i put a screenshot here… what was wrong with it? (or where is it in the app?)

**Comment by brandonhaslegs** [comment]
Does this fix it? I doubt it, I didn't do much

![270F](https://github.com/radicle-dev/drips-app-v2/assets/4406983/3d3ecf2d-1653-4de9-bf59-5cceb3709168)

**Comment by brandonhaslegs** [comment]
Okay this is because the Level-1 primary color is a transparency instead of a hex code.

Here's a new asset, it includes a `background` shape behind that shape that hides the pencil stuff that was showing through before.

![270F](https://github.com/drips-network/app/assets/4406983/53854010-526e-4742-8bae-94881353ea6e)

**Comment by efstajas** [comment]
For whoever works on this: task is simply to replace the svg markup in `PenIcon.svelte` with the one brandon posted above ☝️ Also make sure that any color variables are replaced with the appropriate CSS vars (see other icon components for reference). E.g. the dark color becomes var(--color-foreground), the blue becomes var(--color-primary), etc.

**Comment by evvvritt** [comment]
Seems fixed?
_svg above:_
<img width="432" alt="Screenshot 2024-03-06 at 18 17 47" src="https://github.com/drips-network/app/assets/6071219/5ce60959-001f-4423-986a-24181538a883">
_app:_
<img width="281" alt="Screenshot 2024-03-06 at 18 18 00" src="https://github.com/drips-network/app/assets/6071219/19661129-2f46-4785-be91-f101f67edcba">
