### ISSUE TITLE
On profile view under the drip list round the monthly stream rate up to the nearest

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#525]

**Comment by efstajas** [comment]
@brandonhaslegs still relevant?

**Comment by brandonhaslegs** [comment]
Was it done? I still see it here ![image](https://github.com/drips-network/app/assets/4406983/b0f649c7-4a9d-4a95-99f5-a181c6eeaf15)

**Comment by efstajas** [comment]
Marking as blocked for now. Once amounts are coming from the API, we will build a new `Amount` component, which can include this logic.

**Comment by efstajas** [comment]
So tbh i'm increasingly convinced that it's not the best idea in the world to round, even if slightly, any kind of financial value in a financial app. Those "almost but not quite whole" numbers are in reality actually like that. Please feel free to re-open if you feel strongly

**Comment by brandonhaslegs** [comment]
But I set it to 10 and it showed up as 9.999999. But that seems like a different issue.

Anyway 9.999999 = 10 fight me

also like… this is totally unnecessary
![Image](https://github.com/user-attachments/assets/e45c0bda-1ed0-4bde-8a06-68b843a6dadc)

**Comment by brandonhaslegs** [comment]
eh whatever
