### ISSUE TITLE
BSOD flash

### ISSUE THREAD

**Issue by CodeSandwich** [drips-network/app#531]
After entering https://feature-dependency-funding.drips.network/app of any of sub-pages, sometimes the screen becomes a BSOD-styled error page for a split second before the proper page loads. It's completely random, maybe 1 case in 30? It seems to be easier to trigger when hitting F5 while the page keeps loading.
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/3efde3e7-57d4-45af-85b9-0237f64e6ed4)
 
The console seems to have the regular errors, but the first one is an extra:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/0fc841a0-e5f7-4ca9-af87-940781e5f7f8)

**Comment by efstajas** [comment]
Closing for now, let us know if it happens again 👍
