### ISSUE TITLE
The "Projects" page is vague

### ISSUE THREAD

**Issue by CodeSandwich** [drips-network/app#532]
If I entered the app without thoroughly reading the docs, and didn't know what "projects" are, I'd be very confused. The only way to find out that these are actually git repos is to enter the claiming flow.

**Comment by brandonhaslegs** [comment]
Is this still relevant? This is the empty project state, I think it's okay. Maybe it looked different when this issue was made. Maybe we should add "GitHub" to the text?

<img width="678" alt="image" src="https://github.com/drips-network/app/assets/4406983/5ff8d7e6-44eb-4a3f-af7a-0730050cf511">

**Comment by brandonhaslegs** [comment]
Feel free to reopen if I misunderstand you.
