### ISSUE TITLE
Maintainers splitting screen papercuts

### ISSUE THREAD

**Issue by CodeSandwich** [drips-network/app#542]
In this form:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/fb389f6f-d17e-4163-ab12-3f1c4cea9652)
I've stumbled upon a few papercuts:
- [ ] I didn't understand that `Ethereum address or ENS name` is a text field. I was trying to click the `Add` button and since it was grayed out, I've concluded that it's an undeployed or unavailable feature to have multiple maintainers. Only because I remembered seeing multiple maintainers during a weekly meeting, I've tried again and discovered that it's a text field.
- [ ] The percentage text field doesn't work when clicking on it unless you click on the number. When `0%` is displayed, most of the text field frame is actually inactive. At first I thought that I'm doing something wrong or I can't set a custom percentage, because clicking in the frame wasn't bringing focus.
- [ ] The manual input of percentages is cumbersome. The only easy input are the buttons, which only support the simplest setups. It'd be great to have at least a slider near each percentage field, so the user doesn't need to type. A large slider with like in the maintainers-dependencies screen would be super cool, but probably tricky to implement reasonably. Currently it's not a trivial task to take 5% from one contributor and give it to another, you need to either do the math in your head or do some magic with selecting checkboxes and pressing buttons to clear and restore the other maintainer's percentage.
- [ ] The division into the maintainers and dependencies is artificial (which is fine), but it also feels artificial (which isn't). The division into dependencies and maintainers is 2 steps deep, in order to skim 10 percent off of one maintainer and give it to one of the dependencies you need to step back into the maintainers-dependencies division, then fix the maintainers division, and then give the 10% to the dependency. In the end it's pure cosmetics, both maintainers and dependencies are just splits receivers, the whole division is artificially deepened.

**Comment by efstajas** [comment]
Most (all) of these should be resolved since Everett's redesign of the component — but of course feel free to reopen if something remains 👍
