### ISSUE TITLE
A bold claim about splitting funds

### ISSUE THREAD

**Issue by CodeSandwich** [drips-network/app#545]
At the end of the repo claiming flow there's this frame:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/d04f8426-54e3-4fb8-8ec7-55c3c52e6576)
The last claim is rather bold, we don't have the splitting bot yet, and even if we do, we can't guarantee that every repo will have its streams collected and split exactly once every 7 days. Also funds received from splits (and gives, but we don't expose that for now) can be split immediately.

**Comment by efstajas** [comment]
Closing since we're now definitely generally committing to "funds settling" once a week.
