### ISSUE TITLE
skip splitting dependencies in claim project flow

### ISSUE THREAD

**Issue by xmxanuel** [drips-network/app#563]
As a user, I want to add my dependencies later.  They user might clicked on a 60/40 split but was unaware that it needs to happen in this flow. 

I want to have the option `don't add dependencies`. Maybe with a button or explaining to the user that they have to go back to two screens.

![no-change](https://github.com/radicle-dev/drips-app-v2/assets/5212495/112a4ef9-65cf-4bc0-919b-494ac80f2321)

**Comment by efstajas** [comment]
IMO it's good to make this step not super easy to dismiss. It would probably increase the % of projects with a 100% maintainers split.

Everyone, feel free to reopen if you disagree.
