### ISSUE TITLE
missing why explanation in claim project flow

### ISSUE THREAD

**Issue by xmxanuel** [drips-network/app#566]
Currently, only the steps are explained but not `why` this step needs to happen.

Since the key target group is developers, this question will naturally appear in their minds. 

![missing why](https://github.com/radicle-dev/drips-app-v2/assets/5212495/0a382346-2d22-4aa9-8577-10b15d4bae25)

I would like to have a sentence explaining, why this needs to be done.

**Comment by brandonhaslegs** [comment]
Isn't the answer to why I need do this "To verify you are the owner of this project" ?

**Comment by brandonhaslegs** [comment]
Feel free to reopen if I misunderstand you.
