### ISSUE TITLE
difference between verified and not verified projects not immediately clear

### ISSUE THREAD

**Issue by xmxanuel** [drips-network/app#569]
![difference between verified projects](https://github.com/radicle-dev/drips-app-v2/assets/5212495/51a3b494-52ff-42be-b615-822c1380516c)

I checkmark similar to twitter/instagram might be easier to understand instead of a colorful icon.

**Comment by efstajas** [comment]
@xmxanuel The designs call for this separate "Unregistered projects" section in the list editor where unregistered project are added. We didn't get around to implementing this yet. Do you think this makes sense as a solution?

<img width="854" alt="Screenshot 2023-07-12 at 12 03 19" src="https://github.com/radicle-dev/drips-app-v2/assets/1018218/73d4917f-98bb-4342-9689-1ed44ac75bde">
