### ISSUE TITLE
feature request: Drip List selection from verified projects

### ISSUE THREAD

**Issue by xmxanuel** [drips-network/app#571]
As a user, I want to explore the list of verified projects when I am creating my Drips List.

**Comment by brandonhaslegs** [comment]
Nevermind this is not completed.

**Comment by efstajas** [comment]
I think that this might lead to people splitting less to unclaimed projects, which might slow down tree growth. Closing this for now, if anyone disagrees feel free to reopen.

**Comment by brandonhaslegs** [comment]
Yeah kinda sends the wrong message.

**Comment by jo-elimu** [comment]
> As a user, I want to explore the list of verified projects when I am creating my Drips List.

@xmxanuel What do you mean by "verified"?

**Comment by brandonhaslegs** [comment]
@jo-elimu He meant a GitHub repo who has claimed on Drips (versus a GitHup repo that is not claimed on Drips).
