### ISSUE TITLE
Make it possible to fund a list with multiple tokens

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#611]
- [x] Add all tokens being streamed here
<img width="1091" alt="image" src="https://github.com/radicle-dev/drips-app-v2/assets/4406983/67e838d1-56e6-485d-96c5-68f1115ff415">

---

- [x] Make this value a Fiat value that sums up the total tokens that were streamed/donated so far
- [x] make it expandable to show the total amount of each token that has been streamed so far [Figma here](https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=3758-35112&mode=design&t=H7jfGgnlzJ5UsPP4-4)
<img width="398" alt="image" src="https://github.com/radicle-dev/drips-app-v2/assets/4406983/5fa86ba3-fe45-4943-84f3-d09e67b05d9a">

---

- [x] Add an option for streaming a new token or editing specific token streams if you have multiples 
~~- [ ] remove the "edit stream rate" button here because you have to edit the stream rate on a per-token basis~~
<img width="707" alt="image" src="https://github.com/radicle-dev/drips-app-v2/assets/4406983/62f2e8e1-0283-43a4-a7b2-6c97e0929bff">

---

- [ ] add option to add multiple token streams in the drip list set up flow

**Comment by brandonhaslegs** [comment]
@efstajas So there will also be multiple stream rates in a single stream too, right.

**Comment by efstajas** [comment]
No, it'll be just one stream rate per stream, but you can have multiple streams going at different stream rates to the same drip list.

I wonder if we should allow streaming the same token in two separate streams to the same drip list. I don't see any reason you'd want to do that, so probably not?
