### ISSUE TITLE
Text should cut off at the edge of the black shape, not before

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#617]
Notice how the text cuts off based on an interior container. ain't right

<img width="215" alt="image" src="https://github.com/drips-network/app/assets/4406983/93ff4042-da95-4bb8-baa8-060fc0378981">

**Comment by efstajas** [comment]
it should probably just use ellipsis, no?

**Comment by brandonhaslegs** [comment]
yep

**Comment by brandonhaslegs** [comment]
it used to didn't it

**Comment by efstajas** [comment]
yeah it did. idk what changed, will check!
