### ISSUE TITLE
Add fiat value next to each percentage in a drip list

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#624]
<img width="1020" alt="image" src="https://github.com/drips-network/app/assets/4406983/a595384e-56a4-4ae3-88ac-45ee9a5c2e91">

**Comment by efstajas** [comment]
problem here is that we can't really compute a "per month" value for drip lists anymore now that _splits_ to drip lists are possible. We could show a total value though

**Comment by brandonhaslegs** [comment]
okay this was more of a question anyway of whether it should remain in the design file. will remove it for now
