### ISSUE TITLE
Add new Drip Lists icon

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#637]
And replace everywhere where we previously used the `ledger` icon with this new icon.

https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=3940-111928&mode=design&t=4NiojBrNJ65yw0GK-4

<img width="572" alt="image" src="https://github.com/drips-network/app/assets/4406983/5e6d9eee-9679-45f2-aca9-bf9f445645ad">

**Comment by evvvritt** [comment]
do I/we need to add it to the `radicle-design-system` with this same kinda copyright like the other icons? (or do we have some in our own repo? cc @efstajas)
```
<!--
  Copyright © 2022 The Radicle Design System Contributors

  This file is part of radicle-design-system, distributed under the GPLv3
  with Radicle Linking Exception. For full terms see the included
  LICENSE file.
-->
```
