### ISSUE TITLE
maybe a hint about adding new tokens in Create Stream modal?

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#640]
thought it was a bug that there was no prompt to "Add a token" below my WETH token row

feels a bit odd to have a single row selected?
maybe add a hint or ideally the same "+ Add a token" row that either opens the Add Funds modal or a message?

@efstajas / @brandonhaslegs wdyt

<img width="712" alt="Screenshot 2023-08-29 at 14 57 45" src="https://github.com/drips-network/app/assets/6071219/e0336afc-6ff1-4b79-b184-c365991dd19e">

**Comment by brandonhaslegs** [comment]
Yeah we talked about adding the tokens you have a balance in to the top of this list, but still showing all tokens, and if you don't have a balance in one of them, then the flow would take you to the add funds flow.

Here is a design of how I imagine it https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=3978%3A164055&mode=design&t=S4fdyPLF5eDq9Z0z-1

**Comment by efstajas** [comment]
#1299
