### ISSUE TITLE
Link "Supported by" avatars to relevant profile pages

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#644]
<img width="745" alt="Screenshot 2023-09-05 at 11 40 20" src="https://github.com/drips-network/app/assets/4406983/e33abed5-94c6-4b92-b273-aff3ec70111b">

More context from Bordumb [here](https://discord.com/channels/1096003917717983252/1148164943791804426/1148164943791804426)

**Comment by evvvritt** [comment]
That uses the avatar Pile component: "( ) ( ) ( ) +16" 

should you be able to click each avatar, and click "+16" opens a modal of all supporters?

or would clicking the pile open the modal?

**Comment by brandonhaslegs** [comment]
> be able to click each avatar, and click "+16" opens a modal of all supporters?

That sounds good yeah.
