### ISSUE TITLE
Add "small modal" or "alert modal" to design system

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#646]
Small alerts for small things. Standard UI element we're just missing.

Here's the link to the Figma component https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=4024-9608&mode=design&t=k9NCWB1By9fKPLP0-4

**Comment by efstajas** [comment]
Let's track this as part of a specific feature where we need this rather than just adding it to the design system.

**Comment by efstajas** [comment]
Closing after another discussion with brandon^^
