### ISSUE TITLE
Change Delete stream modal to small modal

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#647]
*Note: #646 is required before doing this*

<img width="948" alt="image" src="https://github.com/drips-network/app/assets/4406983/eac9930e-c38d-41c3-90ee-88ec4a3e24a6">

**Comment by efstajas** [comment]
@brandonhaslegs could you elaborate why you think this is needed? doesn't the existing modal look & work fine? if you disagree, could you re-open but expand the task with a list of all modals that should be more narrow like this?

**Comment by brandonhaslegs** [comment]
Small modals are just for a simple quick question or notice, just like this Delete Stream modal. No multiple steps and nothing more than a headline and a bit of text. It's a normal UI element. In Material Design it's called a Dialog I think

![Image](https://github.com/user-attachments/assets/ab46e9e2-5983-40bd-b2ba-a2a9cc19ffcb)
![Image](https://github.com/user-attachments/assets/eab80afc-7d30-4348-a246-64672d7c89f9)
![Image](https://github.com/user-attachments/assets/582bab2a-357c-4cb5-a8f3-6a8d0e00b7f7)
![Image](https://github.com/user-attachments/assets/161cfe64-1ce5-4efa-8afb-e7597761bcbe)

**Comment by efstajas** [comment]
Tracking this as part of #656
