### ISSUE TITLE
Update features section

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#649]
Copy edits from Alexa.

---

**You’re in control**
Your data and funds are yours forever. Drips runs fully on sovereign user-controlled infrastructure.

⬇️

- [ ] **User controlled data**
Full sovereign infrastructure for maximum data security.

---
Drips is entirely open-source, and doesn't charge anything extra on top of network gas fees.

⬇️

- [ ] Free to use beyond covering the cost of gas

---

Use ERC-20 tokens “as is”. No need to wrap them or trust a third party with your tokens.

⬇️

- [ ] No need to wrap them or trust a third party with your tokens.

---

**One contract. One payment graph.**
Drips uses one smart contract for streaming and splitting, enabling effortless and flexible token routing.

⬇️

- [ ] **One contract**
Drips uses one smart contract for streaming and splitting.

---

- [ ] Remove:

One balance for all your streams
Fund multiple streams using one account balance in a single transaction.

---

- [ ] Remove:

Coming soon: Multi-Chain
Available on the most popular EVM networks: Ethereum, Mainnet, Polygon, Optimism.

---

- [ ] Since we're removing 2 of these feature sections, make the whole section just 4 cards across, instead of 3x2.
![image](https://github.com/drips-network/app/assets/4406983/05cbf836-4745-4a04-a32b-e9808d94daf3)

**Comment by christian-carey** [comment]
Hi @brandonhaslegs. I am new to open source contribution, but I'd like to join. Can I give this issue a go?

**Comment by brandonhaslegs** [comment]
@christian-carey Yep, feel free to give it a go. I'm here (or @efstajas @evvvritt @jtourkos) for any questions you've got.

**Comment by christian-carey** [comment]
I'm on it. I am setting up my development environment

**Comment by christian-carey** [comment]
Hi @brandonhaslegs I followed the copy from the issue, and I have this:

![Screen Shot 2023-09-07 at 5 09 08 PM](https://github.com/drips-network/app/assets/113315529/c2a7b1f3-38c3-4d3b-82bf-2a0a60a9604f)

I noticed in the preview screenshot that some of the wording is different. Should I follow the wording of screenshot you provided, or stick with it as is I have it now?

**Comment by brandonhaslegs** [comment]
@evvvritt What do you think?

**Comment by evvvritt** [comment]
- [ ] Left card missing a `.` at end of sentence
- [ ] "Full sovereign..." should be "**Fully** sovereign..."
- [ ] Third card is repetitive "No need..." repeats. I'd suggest:
> **No need to wrap tokens**
> Stream native tokens. No need to trust third-parties with your funds.

**Comment by christian-carey** [comment]
How is it now?
![Screen Shot 2023-09-08 at 9 35 58 AM](https://github.com/drips-network/app/assets/113315529/7ae24799-71e6-4de0-937a-40e4cad72e1c)

**Comment by evvvritt** [comment]
Ah, can we do 
...No need to trust third-parties **with funds.**
so it can fit on two lines? 🤓 
thanks!

**Comment by christian-carey** [comment]
Sure!

**Comment by christian-carey** [comment]
If you're happy with the changes, I have opened a pull request:
https://github.com/drips-network/app/pull/669
