### ISSUE TITLE
Copy update on Drip List headline

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#650]
Pass it on: Support your software dependencies

⬇️

Fund projects you depend on

**Comment by efstajas** [comment]
@lftherios "Fund" is legally problematic, right?

**Comment by brandonhaslegs** [comment]
btw this is one of the copy edits from Alexa after she looked at the site. But @evvvritt and I discussed some other copy changes for the home page and I wonder if this is still relevant?

Also we surely already use "fund" somewhere right?

**Comment by efstajas** [comment]
I think best if for the LP we collect copy updates in batches so we can run things by Ange / lawyers if necessary. Agree it sounds a lot nicer though 😬
