### ISSUE TITLE
Improve error handling for Fiat Estimates websocket connection to Binance

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#668]
If the WSS connection to binance fails for some reason, we currently just display infinitely loading fiat estimates. Instead, we should:

1. Retry
2. Retry again
3. Display some explicit error state that says something like "Fiat estimates unavailable"

**Comment by evvvritt** [comment]
Maybe retry with https and just have a static value? (is websocket really necessary?)

**Comment by efstajas** [comment]
Closing since we now just fetch static values from Coinmarketcap via HTTPS.
