### ISSUE TITLE
drip list appearing on profile that doesn't own it?

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#674]
The [Radworks Software Dependencies](https://www.drips.network/app/drip-lists/50330452048867519181028275890986093327647919805766323166158196453514) list says it's owned by cloudhead.eth but also appears on [0x8dA8f82d2BbDd896822de723F55D6EdF416130ba's profile.](https://www.drips.network/app/0x8dA8f82d2BbDd896822de723F55D6EdF416130ba)

<img width="1436" alt="Screenshot 2023-09-19 at 15 24 32" src="https://github.com/drips-network/app/assets/6071219/e6bbd18e-47c3-4bca-9eaa-6a76c438c30f">

**Comment by efstajas** [comment]
Hey @evvvritt unless i'm missing something, it says that Radworks Dependencies is owned by [0x8dA8f82d2BbDd896822de723F55D6EdF416130ba](https://www.drips.network/app/0x8dA8f82d2BbDd896822de723F55D6EdF416130ba) (which is the radworks treasury), and cloudhead.eth owns "Radicle dependencies". So everything is right, no?

**Comment by evvvritt** [comment]
ohh my bad!
