### ISSUE TITLE
ENS lookup inconsistent

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#708]
On page load and further navigation sometimes ENS names fail to be written in. Unclear if it's a lookup or reactivity issue?

Tested by refreshing on 
- [Radwords Software Dependencies List](https://www.drips.network/app/drip-lists/50330452048867519181028275890986093327647919805766323166158196453514)
- [drips-network.eth profile](https://www.drips.network/app/0xcC7d34C76A9d08aa0109F7Bae35f29C1CE35355A) (or navigating to this profile from the list)

Connected via MetaMask
no messages in the console

anyone else notice this?

<img width="1521" alt="Screenshot 2023-10-04 at 13 06 53" src="https://github.com/drips-network/app/assets/6071219/41236921-0894-4d2b-8206-7d4491a01ec6">
<img width="1521" alt="Screenshot 2023-10-04 at 13 09 09" src="https://github.com/drips-network/app/assets/6071219/346ac6b5-c62b-438e-be2b-ff6e47082829">

**Comment by evvvritt** [comment]
Perhaps some bad timing / logic with ensStore.connected?

**Comment by efstajas** [comment]
Also Drip List badge doesn't trigger ENS lookup for owner

**Comment by brandonhaslegs** [comment]
This guy also reported this in our Discord https://discord.com/channels/1096003917717983252/1180202620154020032/1180202620154020032

**Comment by efstajas** [comment]
Fixed the problem where the drip list badge wouldn't load ENS: https://github.com/drips-network/app/commit/5dd56421663dc878088dd6ef3fe85aea07460446

**Comment by evvvritt** [comment]
Not really seeing this issue anymore so going to close but someone can reopen if need be
