### ISSUE TITLE
Add ability to not create support stream for new drip list

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#711]

**Comment by brandonhaslegs** [comment]
We decided on these two steps. Left is for now, right is after one time donations launch
<img width="1132" alt="image" src="https://github.com/drips-network/app/assets/4406983/083fc89c-1fb7-4d8f-9b1e-66b75b663bf0">

**Comment by brandonhaslegs** [comment]
also in the final review step needs to be changed too 
<img width="740" alt="image" src="https://github.com/drips-network/app/assets/4406983/aa978ebd-6d3c-49ca-bd2e-2e85652d0c75">
