### ISSUE TITLE
Drip List selector after clicking "Support this project / drip list"

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#712]
<img width="577" alt="Screenshot 2023-10-04 at 15 40 26" src="https://github.com/drips-network/app/assets/1018218/613f0f35-ae62-4002-98be-46493b4485f5">

**Comment by efstajas** [comment]
@brandonhaslegs I just realized you may have multiple drip lists called the same thing… Probably not something we have to worry about for now, but maybe we can add some more distinctive attributes to the list? E.g. a pile of the first 4 items on the list, or maybe a total count of recipients…

**Comment by brandonhaslegs** [comment]
yeah that's smart let's do something like that. will work on something

**Comment by evvvritt** [comment]
This didn't get closed with the PR?
