### ISSUE TITLE
Make copy URL button consistent

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#716]
The copy button next to GitHub URLs is displayed by default, but it should be hidden and reveal on hover.
<img width="237" alt="image" src="https://github.com/drips-network/app/assets/4406983/1e676b7d-b972-456b-9e51-c5f938eb0ff0">

This one works right
<img width="157" alt="image" src="https://github.com/drips-network/app/assets/4406983/14f14929-7847-4f04-a477-bcacd43c7dea">

Would be great if this was a component so that it worked the same way everywhere.

**Comment by evvvritt** [comment]
The `ethers-io/ethers.js` text links to the Github page, while copy button let's you copy it I guess to put into a drip list? (or was there another reason @efstajas?)

I would vote keeping the URL link but removing the copy button since we have the Support sidepanel. wdyt?

**Comment by efstajas** [comment]
> Would be great if this was a component so that it worked the same way everywhere.

It is! Making it collapse like that would just mean setting one prop to `false`.

> The ethers-io/ethers.js text links to the Github page, while copy button let's you copy it I guess to put into a drip list? (or was there another reason @efstajas?)

Yeah exactly, that's what I was thinking. Right now you need to copy GitHub URLs to put them on Drip Lists, and I kinda felt that to be a pretty common interaction so didn't want the copy button to be hidden. Though if you're trying to copy the GitHub URL from the project page, I guess you'd hover over the GitHub link anyway, at which point you'd discover the copy button.

> I would vote keeping the URL link but removing the copy button since we have the Support sidepanel

I think we still need some copy functionality. You may already actively be in the process of building a Drip List, at which the sidepanel won't help you.

I think we should:

1) Add support for pasting **drips project URLs** in addition to GitHub URLs into the List Editor
2) Add a persistent "Share / Copy Link" button to project & address profiles just like we have on Drip Lists already
3) Make the copy button on the GitHub link on project profiles hide and only appear on hover, like Brandon requested

**Comment by brandonhaslegs** [comment]
i made issues for the other things

**Comment by efstajas** [comment]
It looks like everything here is resolved as a result of various changes that happened in the meantime, except the ability to paste a Drips Project URL into list editors. Created a new task for this here: #1300
