### ISSUE TITLE
Update "Add USDC funds" Modal

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#719]
Remove the word "Funds" from this title.

(We have "Collect USDC" and "Withdraw USDC" but "Add USDC" is the only one with "funds" in the title.)

<img width="501" alt="image" src="https://github.com/drips-network/app/assets/4406983/a9e19c09-dd78-4063-8c0a-0421eeb4a199">

**Comment by DustyDogCodex** [comment]
Hi @brandonhaslegs 

I would like to work on this issue. If no one else has been assigned, please assign this issue to me so I can help you resolve it.
If you could just tell me the location of this particular modal, I can get started on fixing it for you!

Thanks!
