### ISSUE TITLE
Profile: move active sections to the top

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#723]
Nicer to see the drip list than the empty projects section ya?
hide or put empty sections down the page?
<img width="1521" alt="Screenshot 2023-10-09 at 13 55 57" src="https://github.com/drips-network/app/assets/6071219/f1d68a78-df78-4f02-ae63-af2be457d400">

**Comment by evvvritt** [comment]
closing since pending redesign (#853)

**Comment by efstajas** [comment]
When we started rendering this page server-side we already made it auto-collapse empty sections. IMO that settles it.
