### ISSUE TITLE
Improve Support Drip List flow

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#728]
- [ ] 1. If Creating a Drip List, already add it to the list (currently have to click Add)
- [ ] 2. Put added drip list at the top of the list with a blue background (design: @brandonhaslegs)

issue 1: (shouldnt have to click Add)
<img width="1521" alt="Screenshot 2023-10-11 at 15 14 52" src="https://github.com/drips-network/app/assets/6071219/7f15f107-318f-400b-bc15-c75adbe050c8">

**Comment by brandonhaslegs** [comment]
It doesn't need the blue background if you're creating a new Drip List, only if you're adding to an existing Drip List

**Comment by brandonhaslegs** [comment]
So like this 
<img width="534" alt="image" src="https://github.com/drips-network/app/assets/4406983/c0c1fe16-4af9-4cae-83bd-997a0f144150">

**Comment by evvvritt** [comment]
completed with #779
