### ISSUE TITLE
persistent, share button on project page

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#742]
Add a persistent "Share / Copy Link" button to project & address profiles just like we have on Drip Lists already

**Comment by efstajas** [comment]
1) Make the current "copy github url" button only show up on hover over gh badge
2) add a persistent share-button.svelte to the profile
3) allow pasting drips.network project URLs into drip list members editor alongside github URLs

**Comment by brandonhaslegs** [comment]
i don't know what 3. has to do with this, but it looks done to me.
