### ISSUE TITLE
Introduce Drip List concept in Drip List creation flow

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#761]
I think it'd be nice to clearly introduce what a Drip List is and quickly summarize how it works when you enter the creation flow, as part of an intro step in the flow, with some nice visuals. Off the top of my head, the most important points:

- Split funds to up to 200 GitHub repos, Ethereum addresses or other Drip Lists at a time
- Edit recipients and your support anytime 
- Public and supportable by others

It should also link to [this doc ](https://docs.drips.network/support-your-dependencies/overview) for more info.

**Comment by brandonhaslegs** [comment]
Here's an idea on this:

<img width="626" alt="image" src="https://github.com/drips-network/app/assets/4406983/e1173beb-a251-45f9-a620-7c4d47bf6cb0">

https://www.figma.com/design/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?node-id=8248-30314&t=Qa09vGfayYihfZTL-4
