### ISSUE TITLE
Put Drip List title & description above list editor in creation flow

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#766]
The title & description are generally above the list, so it makes more sense for these inputs to appear above the list editor in the creation flow as well. The list is expected to grow longer too, pushing those inputs down, which is a bit weird.

**Comment by brandonhaslegs** [comment]
yeah I did it like this because it seems like you would want to start creating your list first before you name it. and if you start with naming it and adding a description it just seems like a barrier to creating it.  But I'm fine with it I understand why it seems weird.
