### ISSUE TITLE
Explore page

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#769]
Design is here:
https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=5247%3A8248&mode=design&t=bC88zWn40U70EaiO-1

![image](https://github.com/drips-network/app/assets/4406983/23764dfe-2093-47cd-9c1c-06aa32a60812)

**Comment by evvvritt** [comment]
curated sections that can include any project, drip-list, or user (eg "Awesome Web3", ...)
