### ISSUE TITLE
Change "Members" to "Recipients"

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#773]
I just don't think they're "members" really. seems like they're somehow involved in the Drip List… instead of just receiving money

<img width="446" alt="image" src="https://github.com/drips-network/app/assets/4406983/1af50795-e4ff-41fc-8933-add15276380a">

**Comment by evvvritt** [comment]
I was thinking member is more flexible and accomodates lists as curation, not just splits:
> ethers is a member of the Awesome Web3 list

vs saying something is a recipient of a list doesn't make sense?

**Comment by brandonhaslegs** [comment]
Welp, I think the exact opposite. Member implies the person joined. Like they are somehow an active part of this group, when they might not even know they're in it.
