### ISSUE TITLE
Add a link to transaction in which stream was established on Etherscan

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#778]
https://discord.com/channels/1096003917717983252/1096004153085530253/1169676583003504730

**Comment by brandonhaslegs** [comment]
Design here:
<img width="400" alt="image" src="https://github.com/drips-network/app/assets/4406983/f94023d1-ff18-4057-83b5-4e11a3ef7866">

BTW I think the link being up there with the other buttons is fine/good. I don't see a clear place for it below, and also I think it could be a common action anyway! Don't need to toss it down at the bottom.

**Comment by evvvritt** [comment]
Fine with button but fairly common practice, Etherscan links are linked to timestamps. In our case we could link both created and updated timestamps.

Or even topups if we add a history of that at some point.

**Comment by brandonhaslegs** [comment]
<img width="415" alt="image" src="https://github.com/drips-network/app/assets/4406983/16d16283-ec5f-43af-8783-fd573fa7a706">

**Comment by evvvritt** [comment]
Ha sorry, I meant "fine with button up there*" but common to find etherscan links like so:
<img width="673" alt="Screenshot 2023-11-08 at 15 43 01" src="https://github.com/drips-network/app/assets/6071219/5adabb1f-4aed-488a-ae5e-eda9deacdcef">
what do we think?
(or could be etherscan logo as ghost icon button)

**Comment by brandonhaslegs** [comment]
Yeah it's just invisible where that link is going. Could add a tooltip, but what about mobile, and also why? I know it's normal to do this, but doesn't mean it's good.

**Comment by brandonhaslegs** [comment]
Etherscan ghost icon could be a good compromise, yeah!

**Comment by evvvritt** [comment]
Cool, let's do it
