### ISSUE TITLE
Remove references to V1

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#783]
profile
![image](https://github.com/drips-network/app/assets/4406983/133621b1-ec2f-4f1a-9aa7-576e5ced6248)

and in the footer
<img width="155" alt="image" src="https://github.com/drips-network/app/assets/4406983/85bd0c02-4932-4828-9f42-4f5f7e968d1a">

**Comment by evvvritt** [comment]
Maybe good to have it somewhere though? Landing page footer seems like least intrusive
Or is it always in our docs?
cc @efstajas

**Comment by efstajas** [comment]
I think we can remove the references completely, I don't think they provide any value anymore. 🤷
