### ISSUE TITLE
Update stream modal

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#788]

**Comment by evvvritt** [comment]
1. Select token should allow you to select ANY token and then the modal should evaluate if you need to topup for that token
2. be able to search ENS/EthereumAddress/Project/DripList

**Comment by brandonhaslegs** [comment]
Don't think there's any design needed here? We have this:

![image](https://github.com/drips-network/app/assets/4406983/24fb1ba5-be78-414b-9caf-00f88abca9d8)

and this

![image](https://github.com/drips-network/app/assets/4406983/1f5d9a5f-d42e-4e89-9a66-651e9121178e)

What else is needs to build this?

**Comment by evvvritt** [comment]
I guess handling if someone doesnt have a balance in selected token, how it should guide you? maybe if technically possible, if you dont have a token funded in your account, new topup field should appear, and ideally show your wallet balance, with max toggle/button (should be some prior design for that type of input)
wdyt @efstajas

**Comment by evvvritt** [comment]
ah, stream name is also currently required (but i dont really think needs to be imo)

**Comment by efstajas** [comment]
#1299
