### ISSUE TITLE
Solution for claiming a project with multiple owners

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#791]
Just trying to prevent maintainers from claiming a project on Drips and draining all the funds without telling other maintainers.

Context here https://discord.com/channels/1096003917717983252/1096004153085530253/1171897580666503269

**Comment by efstajas** [comment]
We can't really do much here, if someone manages to sneak a file that maintainers don't understand into a GitHub repo, they can do all kinds of nasty stuff, including redirecting GitHub Sponsors funds etc. Write access, or approving a PR = a lot of trust.
