### ISSUE TITLE
Add Funds Modal - Show tokens the connected wallet has

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#806]
In the add funds modal,
- [ ] move tokens that the connected wallet owns to the top of the list
- [ ] show amount

<img width="410" alt="image" src="https://github.com/drips-network/app/assets/4406983/51ff0b09-0997-4426-b981-ebe80eea6b5c">

**Comment by evvvritt** [comment]
+ #572

**Comment by efstajas** [comment]
#515
