### ISSUE TITLE
Global collect button

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#807]
[Link to design](https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=5428-24439&mode=design&t=w62qZ0YIaOuW5f8y-4)

Shows when you have settled funds:
<img width="601" alt="image" src="https://github.com/drips-network/app/assets/4406983/8f0a1a50-d82c-43ee-bad4-8bb92fe5116a">

Shows when you have unsettled funds OR no funds
<img width="443" alt="image" src="https://github.com/drips-network/app/assets/4406983/a92cfa79-cc42-469a-a805-23391df21f17">

modal when there are settled funds (unsettled switch not auto selected)
![image](https://github.com/drips-network/app/assets/4406983/117c0545-3757-4893-a7df-0ffbf02a5912)

modal when there re no settled funds (unsettled switch auto selected)
![image](https://github.com/drips-network/app/assets/4406983/7cc69759-2619-4d09-801b-ee994b5f0c54)

modal (mini) when there are no settled or unsettled funds
![image](https://github.com/drips-network/app/assets/4406983/08d06578-7b71-4bc0-b7b4-ff3556bb520b)

**Comment by efstajas** [comment]
I think the only thing we should probably add is the "settlement" copy we currently have in the collect modal. Something that says "income updates once a week" alongside the next settlement date.

**Comment by brandonhaslegs** [comment]
I came up with two options for the mobile placement of the collect button:

![image](https://github.com/drips-network/app/assets/4406983/7a5dfb25-bf4a-41ce-9142-52c61ef074e3)
![image](https://github.com/drips-network/app/assets/4406983/c53bbdb8-ed21-4c61-a1ad-eadd50ec924e)
