### ISSUE TITLE
New support flow

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#812]
[Design is here](https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=5437-12293&mode=design&t=1jI7qNnOKnlkzS7g-4)

Click Support on a Profile, Project, or Drip List.
![image](https://github.com/drips-network/app/assets/4406983/994ce549-3fd5-43db-b012-385134450179)

---

Support button transforms into three buttons
![image](https://github.com/drips-network/app/assets/4406983/f13685d4-f171-463e-8a30-af02a48f211e)

---

Like this (but open to fun ideas…)
![Expand Button](https://github.com/drips-network/app/assets/4406983/7f9735cf-a367-427e-a1ca-f9c4d4e8af9f)

---

If the user clicks Support Stream
![image](https://github.com/drips-network/app/assets/4406983/8e33ede9-0b33-4b41-86c5-9becd10b1955)

---

If the user clicks Single Donation
![image](https://github.com/drips-network/app/assets/4406983/51e8ca97-7850-4f8a-9861-ed9542ba4b10)
Note 1: Check box is checked by default. This is to prevent having to top up.
Note2: Check box becomes available if user selects token that has a balance in their Drips account.
Note 3: If they uncheck that box, they go into the top up flow.

---

If the user clicks Drip List (opens normal flow)
(if drip lists exist)
![image](https://github.com/drips-network/app/assets/4406983/4a03f350-6944-49f7-ad42-ab6399dcdf34)

---

if creating new list, or no lists exist
![image](https://github.com/drips-network/app/assets/4406983/5457630e-f347-496e-88ca-b876931eeda8)

**Comment by evvvritt** [comment]
[initial feedback/discussion](https://discord.com/channels/1096003917717983252/1172205042015674460/1174708173245005824)
