### ISSUE TITLE
Make "Stream title" not a necessary field

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#814]
Would this be okay @efstajas?

**Comment by evvvritt** [comment]
I also support this

**Comment by brandonhaslegs** [comment]
We'd need to come uo with a way to display the "title" of a stream when it doesn't have a title though.

**Comment by efstajas** [comment]
Ya sure, works for me 👍 The app already handles missing titles for "unmanaged" streams created from outside the app. They just show up as "Unnamed stream"… which we might wanna tweak if we make this a "feature"

**Comment by brandonhaslegs** [comment]
yeah, for sure. good that there's already a default name, I was thinking something that describes the nature of the stream. For example, takes the funder's ENS name and the receivers ENS name or project name and automatically generates a title.

**Comment by efstajas** [comment]
I don't think there's a good reason for doing this — we're going after larger orgs that would create these streams, and having them think a little bit to give a meaningful name instead of going with a generic default will result in better looking data IMO. Feel free to reopen if you disagree ✌
