### ISSUE TITLE
Nicer error modal for flows

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#827]
Right now errors are really ugly and there's usually a clear message we could display and have like an expand button for the full error.

Also, let's not show error when they reject the tx? Just auto go back...

<img width="1531" alt="Screenshot 2023-11-22 at 15 25 17" src="https://github.com/drips-network/app/assets/6071219/8e42a9f2-6f04-4d37-bb8f-7d110efc7b6d">

**Comment by brandonhaslegs** [comment]
- Change "Woops" to "Oops" or "Whoops". I don't think I've ever seen "Woops"
- Is there some way to write these (the actual readable part) in a way that's more normal sounding or are the Network errors we can't control? Like "Relation  goerli.GitProjects  does not exist." doesn't really tell me much either.

But here's an updated desgin:

![image](https://github.com/drips-network/app/assets/4406983/29b855fd-dd8e-4da4-9320-713e605cf339)

**Comment by evvvritt** [comment]
hmm, don't think so. ideally we write nicer messages in the code? 🤔
