### ISSUE TITLE
List drip-lists / projects in the dashboard of Recipients too (not just owners)

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#830]
Right now you can be receiving splits from a drip list or project but it doesn't show in the _Recipient's_ Dashboard, even though they have claimable money (see screenshot below)

We should show projects + drip lists in the Recipients dashboards as well. Do they need to be distinguished if you own them or are recipient.

**example of Project dashboard for recipient:**
(collecatable amount but no projects)
<img width="1166" alt="Screenshot 2023-11-22 at 16 10 27" src="https://github.com/drips-network/app/assets/6071219/f01065f2-9107-4585-8853-f4a207914864">

**Comment by brandonhaslegs** [comment]
This is covered in #272

**Comment by evvvritt** [comment]
No, that issue refers to address profile pages, not Dashboard of logged in user

**Comment by evvvritt** [comment]
Or let's discuss in the meeting today*

**Comment by efstajas** [comment]
#272
