### ISSUE TITLE
Relink Drips logo from inside the app

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#831]
After we launch Explore, relink the DRIPS logo to the Explore page from within the app (so on any profile, project, stream, etc page).

**Comment by evvvritt** [comment]
There's probably a lot of small issues like this we can bundle with a/the larger Explore issue.

**Comment by brandonhaslegs** [comment]
This wasn't completed just yet

Logo should link to:
1. Connect wallet screen when no wallet connected
2. Funds page if wallet connected
3. Explore page when we launch it

**Comment by brandonhaslegs** [comment]
Or is it tracked somewhere else? can you mention where if you close it again?
