### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#844]
Marketing team wants a blog. If you can put the technical pieces together and put up a sample post I can style it.

**Comment by efstajas** [comment]
Created a (for now private) repo based on a sveltekit static blog starter: github.com/drips-network/blog

Using SvelteKit bc we can re-use our existing theming and components. It'll be a fully static blog, meaning we could host it easily even on GitHub pages. All you need to do to push a new blog post is adding a markdown file to `/lib/posts`, and you can even embed custom Svelte components inside the posts.

The default template looks a bit rough, but it's of course fully customizable, and it looks like this starter is built in a pretty neat way, so it could be great starting point!

**Comment by efstajas** [comment]
Ya. I can set up the basic theming so we can make use of that, then we should be able to just copy-paste styles or even entire components to the blog.

**Comment by efstajas** [comment]
I've pushed the basic radicle-design-system styles, so we can use vars like `color-primary` etc. and typography classes just like in the drips app. Layout is super broken now obviously, but now it's basically just about styling the components. You can go for it if you want, or maybe let's start with a basic design in figma?

**Comment by efstajas** [comment]
> For backend maybe we could use [Decap CMS](https://decapcms.org/) (formerly Netlify CMS)

Tbh I don't think we need a backend, what's wrong with static generation?
