### ISSUE TITLE
Increase the width of the truncation on Drip List list

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#845]
It's unnecessarily truncating things in the list.

<img width="756" alt="image" src="https://github.com/drips-network/app/assets/4406983/d82dcbc4-24a4-4bf0-bbea-c2ed0fdf0ab7">

**Comment by efstajas** [comment]
@evvvritt wasn't it fixed here? 🤔 https://github.com/drips-network/app/issues/755

**Comment by evvvritt** [comment]
ya but [this commit](https://github.com/drips-network/app/commit/4a85a6f4ef58d3861fbb23e5701b19e14afbee7f#diff-a2ba2d3863ec34422fef68e15b8df89f2c5ba6bbe7ad779bf6c600110f6976ebL180) removed it
