### ISSUE TITLE
Accept Drip List URL in stream set up field

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#852]
<img width="741" alt="image" src="https://github.com/drips-network/app/assets/4406983/41d0e231-eea1-43b1-8cf4-300f70498859">

**Comment by evvvritt** [comment]
hmm wouldn't you just create the stream from the drip list's page where you got the URL from though?

**Comment by brandonhaslegs** [comment]
Still think it should be allowed here. It’s fine (or good) to have multiple ways to do something. If someone for any reason wants to stream to a drip list like this (like me in this case) then they should be able to and not be presented with an error.
