### ISSUE TITLE
Show Drip Lists a user is a recipient of on the profile

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#854]
This user is a Drip List recipient, but the profile doesn't show that. It should.

<img width="950" alt="image" src="https://github.com/drips-network/app/assets/4406983/7124f7d0-6001-4d4e-9b37-b031bb4e252d">

**Comment by evvvritt** [comment]
extension to #830

**Comment by efstajas** [comment]
This would be fixed by #272, right? The supporters card will also include Drip Lists and projects splitting to the user.

**Comment by evvvritt** [comment]
Ah true, ya maybe that's enough.

**Comment by brandonhaslegs** [comment]
Yeah true I'm gonna close this.
