### ISSUE TITLE
Projects in one-time donation modal header have wrong preview icon

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#865]
<img width="1012" alt="Screenshot 2023-12-13 at 11 36 20" src="https://github.com/drips-network/app/assets/1018218/be96140f-d595-4942-9ceb-aae759def74c">

It's the wrong way around. It's github logo -> project emoji everywhere except here.

**Comment by evvvritt** [comment]
I think I got this from @brandonhaslegs design but can't find. I actually don't think it's bad? It's nice to see your money is being sent to a thing rather than GitHub? Also if you open their profile their avatar is big and primary. 

But also fine to change

**Comment by brandonhaslegs** [comment]
yeah i switched it because it felt weird the other way

**Comment by evvvritt** [comment]
Let's keep it 😜
