### ISSUE TITLE
Avatar should always have a `foreground` outline

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#887]
Avatar should always have an outline. Right now it's sorta mixed

<img width="769" alt="image" src="https://github.com/drips-network/app/assets/4406983/7dd8ff52-aa3a-4639-90a2-ccac64dbf79b">

**Comment by evvvritt** [comment]
Should also add background color - transparent avi's overlap in Pile component atm

**Comment by brandonhaslegs** [comment]
Yes plz
