### ISSUE TITLE
Display GitHub repo description on project pages 

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#890]
https://discord.com/channels/1096003917717983252/1096004153085530253/1194218858337292390

**Comment by evvvritt** [comment]
as agreed in the product-weekly mtg, use **github repo description** instead of README

**Comment by brandonhaslegs** [comment]
So the project cards already have descriptions in them btw
<img width="890" alt="image" src="https://github.com/drips-network/app/assets/4406983/2df2c0dc-089e-43bd-bdba-eb6cbb6e6ec6">

And then I just added the description here on project pages
<img width="788" alt="image" src="https://github.com/drips-network/app/assets/4406983/65c60628-5b8d-4669-ab07-b5219773fa93">

**Comment by brandonhaslegs** [comment]
By "description" you mean the text in the "about" section right?

**Comment by lovelymahor** [comment]
I want to solve this issue, please assign it to me

**Comment by brandonhaslegs** [comment]
@lovelymahor Go for it! If you need any help getting set up, you can ask @efstajas @jtourkos or @evvvritt
