### ISSUE TITLE
Enhance page descriptions

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#891]
https://discord.com/channels/1096003917717983252/1096004153085530253/1194218858337292390 (point 3 partially)

**Comment by brandonhaslegs** [comment]
So the page description is currently set to be the Drip List description:
<img width="344" alt="image" src="https://github.com/drips-network/app/assets/4406983/f4aea498-da43-480f-aa73-d61f07b83d5c">

But when a Drip List doesn't have a descriptions set, which is common, the description is about Drips which is weird. 
<img width="628" alt="image" src="https://github.com/drips-network/app/assets/4406983/8c97cc7c-f444-4aa6-9154-ae02c368be05">

This description should be something generated that can work for any Drip List, like "$326,134 total, 11 recipients, created by cloudhead.eth"

BTW this is interesting/related, sometimes Google picks up the funded amount and displays it as a product price.
<img width="261" alt="image" src="https://github.com/drips-network/app/assets/4406983/a5f75d97-c1d7-45df-9f1f-a9bd3e2b7172">

**Comment by brandonhaslegs** [comment]
Here is an idea for a description:

`Radicle Dependencies is a fundable Drip List. Anyone can send funds to this list on a one off, or by-the-second basis.`

**Comment by brandonhaslegs** [comment]
And I added another issue for the original task here #1085 because I still think we should do that.

**Comment by efstajas** [comment]
@brandonhaslegs i changed the text slightly: `"${dripList.name}" is a fundable list of open-source projects. Anyone can send one-time or continuous donations.`
