### ISSUE TITLE
Change CTAs on profile to "normal" button style

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#902]
These primary CTAs are really jarring. Should change them to normal (outline) buttons. `background` background and `foreground` outline, with `foreground` text.

<img width="392" alt="image" src="https://github.com/drips-network/app/assets/4406983/ec832fd8-d576-4991-a4ee-0227effe9dae">

**Comment by evvvritt** [comment]
This would also affect the Dashboard pages, that ok?

**Comment by brandonhaslegs** [comment]
Yep I think so. Too many prinary CTAs next to one another is weird no matter where it is.
