### ISSUE TITLE
Drip List details confirmation modal

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#904]
When you change details of a Drip List it tells you to refresh your dashboard, which doesn't make sense. Use either "refresh this page" or "refresh your Drip List".

<img width="724" alt="image" src="https://github.com/drips-network/app/assets/4406983/9c694522-16a1-40ca-8763-482aa98b35c2">

**Comment by efstajas** [comment]
Let's change the second sentence to "Please refresh the page to see the changes."

**Comment by efstajas** [comment]
Yeah, absolutely. There's another task for this: #558 

It will entail invalidating the load function that calls in Drip List data. It'll be seamless, no page reload required.
