### ISSUE TITLE
Avatars should be clickable

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#905]
None of these are clickable, but they should lead to the corresponding profile or project

<img width="521" alt="image" src="https://github.com/drips-network/app/assets/4406983/7509308a-806d-4b07-b8fe-d775f98521c5">

**Comment by evvvritt** [comment]
Hmm idk if I agree— since these "stat" blocks are summaries, isn't it more intuitive that clicking anything in the block takes you to the full sections where you could click individuals?

**Comment by brandonhaslegs** [comment]
I tried clickin 'em

**Comment by brandonhaslegs** [comment]
But linking them to full sections works for me too.

**Comment by evvvritt** [comment]
But they do right now? Clicking each stat block scrolls you down the page.

**Comment by brandonhaslegs** [comment]
okaayyyyyyy i seee. So needs some highlighting when it is clicked. i didn't get what was going on
