### ISSUE TITLE
Rainbow (Injected) doesn't connect after modal

### ISSUE THREAD

**Issue by talentlessguy** [drips-network/app#928]
Hi, I'm using FireDragon (FF fork, ver. 119) and Rainbow extension installed on it.

For some reason after triggering a connection modal, it says "Connected" but nothing actually happens.

I looked in the logs - it seems like it makes requests to a localhost RPC?

![image](https://github.com/drips-network/app/assets/35937217/a55b6f2a-ec2c-46ca-aef6-6715118cf4ba)

I haven't tested Chrome yet but on mobile it works fine

**Comment by evvvritt** [comment]
Hey thanks! feel free to reopen this if you provide the above^ at it persists :)
