### ISSUE TITLE
Automatically suggest dependencies based on package manager files

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#935]
Integrate https://github.com/jtourkos/git-dep-url into our project claim flow to automatically suggest a list of projects to split to.

**Comment by SouravInsights** [comment]
Is anyone working on this? @efstajas

**Comment by efstajas** [comment]
@SouravInsights Not actively at the moment. 

However @brandonhaslegs we should have a rough design sketch before anyone starts working on it. The idea is that as soon as you submit the repo URL, we kick off the dependency parser in the background, and then have the step on which you enter dependency splits pre-filled with dependencies, equal splits. IMO it should tell you in perhaps a blue info box that dependencies have been pre-filled from your package manager file, and also allow you to clear the pre-filled dependencies easily in case you'd rather start from scratch.

Generally, keep in mind that the dependency parsing might fail for any number of reasons, so we can't really "make it a feature", more like a little unexpected convenience thing.

**Comment by brandonhaslegs** [comment]
@efstajas So should be added to the project board too

**Comment by jo-elimu** [comment]
> Integrate https://github.com/jtourkos/git-dep-url into our project claim flow to automatically suggest a list of projects to split to.

An even more advanced version of this would be to calculate how many times a dependency has been used throughout the code, and allocate a higher percentage to the most used dependencies. Using something like https://github.com/ichiwa/dependency-import-counter

**Comment by brandonhaslegs** [comment]
Luckily the step to enter your dependencies is quite a few steps after verifying project ownership, so there will be plenty of time to be pulling suggested dependencies in the background. 👍

<img width="682" alt="image" src="https://github.com/drips-network/app/assets/4406983/a00dfe95-41c3-486c-92f2-44613a259bd1">

As soon as the user starts editing the list, I think this note should disappear.

**Comment by brandonhaslegs** [comment]
From @efstajas 
there were also some concerns about whether it's even a good idea to default to potentially a really long list of dependencies each of which would get a very small percentage of funds. especially considering the impact on cost of splitting those accounts with long split lists.

From **earthwindfirewater**
Based on all of our research into this in the past, as well as our user interviews with funders and devs, I personally don't think this is a good way for us to go. The key issues are:

1) As Jason said, you get a very long list of dependencies whereas the results from pre-v2 user interviews as well as actual users is that most are only interested in specifying 5-10 dependencies. (it would also split the funds up a lot)

2) There is no real way to algorithmically determine the significance of a dependency to a project based on analyzing code alone.

3) Even if it were possible to do a code analysis, many users tell us that there are many intangible factors that strongly affect their dependency funding decisions. For example things like knowing that certain devs need the funding, or specific relationships they have with dependency projects where specific features were built for them.

All-told, I think the automated dependency analysis idea is actually a false trail that many other funding platforms in the space have gone down and I think it's a competitive advantage and differentiator for Drips that we don't have this.

**Comment by jo-elimu** [comment]
> there were also some concerns about whether it's even a good idea to default to potentially a really long list of dependencies each of which would get a very small percentage of funds. especially considering the impact on cost of splitting those accounts with long split lists.

This can be solved by setting a cut-off threshold. For example: Only include the top 10 dependencies.
