### ISSUE TITLE
Support Radicle repos in Drip Lists

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#939]
Should be able to add a Radicle URL to a Drip List

I'd expect to be able to enter this URL into a Drip List, for example. https://app.radicle.xyz/nodes/seed.radicle.garden/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5

<img width="466" alt="image" src="https://github.com/drips-network/app/assets/4406983/c49dc968-522c-4449-8ed9-c0592b5c5d29">

**Comment by efstajas** [comment]
Moving this to our new task board as an idea.
