### ISSUE TITLE
Connect/Collect button shows loading drip on refresh

### ISSUE THREAD

**Issue by jtourkos** [drips-network/app#941]
1. connect
2. navigate to a project's page
3. refresh the page

You'll notice that on the top-right connect/collect button the loading drip animates on top of the connect label like this:

![image](https://github.com/drips-network/app/assets/6360154/3c00507b-d0fa-4cbb-a373-5a6d523b30df)

**Comment by evvvritt** [comment]
@brandonhaslegs wdyt about this? keep or redesign?

one idea was to replace the button icon with the drip animation (it overlays currently because the old apple-style-spinner just overlayed)

**Comment by brandonhaslegs** [comment]
I think it's fine like this.
