### ISSUE TITLE
Round splits weights to reach TOTAL_SPLITS_WEIGHT

### ISSUE THREAD

**Issue by jtourkos** [drips-network/app#944]
Round Projects and Drip Lists splits weights to reach TOTAL_SPLITS_WEIGHT.
This will avoid tiny amounts not being splitted and "stuck" as collectable for the sender.

Relevant files are `GitProjectService.ts` and `DripListService.ts`.

**Comment by efstajas** [comment]
Done with the introduction of new weights-based list editor in multiplayer feature.
