### ISSUE TITLE
Handle unknown tokens better

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#951]
Shouldn't you be able to still go to a stream page even if it's an unknown token?

![image](https://github.com/drips-network/app/assets/4406983/92fa624d-1388-4e23-82e6-9aea2c11c205)

is this really our only option here?
![image](https://github.com/drips-network/app/assets/4406983/eed95ca0-7fcd-4d70-b12f-22d1f95790c9)

**Comment by evvvritt** [comment]
You can once you add the token to your token list
