### ISSUE TITLE
Update etherscan icon

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#952]
![etherscan](https://github.com/drips-network/app/assets/4406983/c497ed32-68a4-4a18-ac90-9daac627f259)

**Comment by brandonhaslegs** [comment]
<img width="565" alt="image" src="https://github.com/drips-network/app/assets/4406983/cfc615fb-8c8d-4397-a9b3-f2b1aed8cb74">

icon still looks wrong

**Comment by efstajas** [comment]
fixed now
