### ISSUE TITLE
Use Twemojis in Drip List titles

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#954]
Example: https://www.drips.network/app/drip-lists/41305178594442616889778610143373288091511468151140966646158126636699

they're just using straight images which changes depending on what OS you're running. Should use Twemoji here, like we do elsewhere.

**Comment by efstajas** [comment]
To do this, 1) run titles and descriptions through `twemoji()` parser function, 2) `sanitize()` the result, 3) render it on the page using `@html` directive.
