### ISSUE TITLE
Add connect button to empty state

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#958]
this empty state should have the connect button under the text

<img width="1195" alt="image" src="https://github.com/drips-network/app/assets/4406983/38974b3b-da3d-4042-9154-efa17838fc1a">

**Comment by sahildotdev** [comment]
hey @efstajas I am working on this..

**Comment by sahildotdev** [comment]
hey, @brandonhaslegs on which route can i find this empty state?
