### ISSUE TITLE
Confirmation before closing edited drip list

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#965]
When you've made changes to a Drip List, add "are you sure" mini modal before allowing user to close modal

<img width="727" alt="drip list modal" src="https://github.com/drips-network/app/assets/4406983/5d551f62-1311-4268-ae9c-2784b8e5dabf">

![image](https://github.com/drips-network/app/assets/4406983/53f497b4-a5b7-4ee9-a7c8-ac6fe2bf077e)

**Comment by efstajas** [comment]
Let's do this for all modals where you'd lose data if you close! We can build this as a generic solution.

**Comment by efstajas** [comment]
#656
