### ISSUE TITLE
Add 4 extra featured projects to explore page

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#971]
So just a second row of four here
![image](https://github.com/drips-network/app/assets/4406983/88e9167f-0dc7-438f-a3c3-051820026490)

My suggestions:
- https://www.drips.network/app/projects/github/NiceNode/nice-node
- https://www.drips.network/app/projects/github/starknet-io/starknet.js
- https://www.drips.network/app/projects/github/snapshot-labs/snapshot
- https://www.drips.network/app/projects/github/efstajas/svelte-stepper
- https://www.drips.network/app/projects/github/heyxyz/hey
- https://www.drips.network/app/projects/github/openlittermap/openlittermap-web

**Comment by SouravInsights** [comment]
this seems pretty straightforward, can work on this.. but quick question, are we manually updating these featured projects list? @efstajas

**Comment by brandonhaslegs** [comment]
@SouravInsights Yeah featured projects are manually added.

**Comment by SouravInsights** [comment]
For visibility, here's a [draft PR](https://github.com/drips-network/app/pull/993) on this issue!
