### ISSUE TITLE
Drip List names shouldn't be truncated on listing page

### ISSUE THREAD

**Issue by efstajas** [drips-network/app#974]
![Screenshot_20240214-183008.png](https://github.com/drips-network/app/assets/1018218/ce59aec5-1e0d-4dba-adf5-ab98be07ea2a)

**Comment by evvvritt** [comment]
Idk I thought it was nice to be able to see the second column and maybe this also leads you to click into them to explore them further. @brandonhaslegs wdyt?

**Comment by evvvritt** [comment]
I like that idea but unless we're truncating, one really long title is going to push the second column it's full width away:
> Open Source Learning Software That Empowers Out-Of-School Children 🚀

**Comment by brandonhaslegs** [comment]
nooo we definitely need to truncate. but was just proposing ideas to show more of the actual list name.

**Comment by evvvritt** [comment]
Then I'm gonna close this truncating issue - feel free reopen and retitle with new design.

**Comment by brandonhaslegs** [comment]
i just meant like this 
<img width="1121" alt="image" src="https://github.com/drips-network/app/assets/4406983/3e7155be-736b-4fe4-bc3f-f5b26f467f25">

**Comment by evvvritt** [comment]
Hmm, I think nice to show the owner's name still though, no? (not just avatar)

**Comment by brandonhaslegs** [comment]
yeah seems fine to add the ens name or address
