### ISSUE TITLE
Add incoming splits to splits card on project pages

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#976]
Just noticed this in the old Figma designs, thought it might be nice to build into the Splits section on project pages

Current Splits section:
![image](https://github.com/drips-network/app/assets/4406983/ecb156ee-6cfd-420d-8490-ad9cb9d7fb4d)

Enhanced Split section (with incoming splits to this project shown):
<img width="798" alt="image" src="https://github.com/drips-network/app/assets/4406983/9f3ff4a7-ae3f-49c1-9ec1-127d226a715f">

**Comment by SouravInsights** [comment]
hey, @brandonhaslegs since i don't have a lot of context on this, can you maybe update the description of this issue with `before` & `after` designs so it's more clear on what needs to be changed exactly?

**Comment by brandonhaslegs** [comment]
@SouravInsights I added some context.
