### ISSUE TITLE
Show projects a user is a maintainer of on user's profile

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#977]
Here is a project
<img width="835" alt="image" src="https://github.com/drips-network/app/assets/4406983/f3af7e5c-d8ba-4f62-bb83-0a8883d603e2">

And here is a maintainer of that project, but the project doesn't show up.
<img width="1169" alt="image" src="https://github.com/drips-network/app/assets/4406983/44b5bc3d-7cba-4565-99dc-6e3d35c7281f">

**Comment by SouravInsights** [comment]
hey, @brandonhaslegs correct me if i'm wrong but the currently logged in user is `distributeddge.eth` right? if so, do you think we should show this info below the profile header maybe? since we are on profiles page, the first thing we would like to see is our profile info like `address/ens` & `pfp` and then the rest of the stuff?

**Comment by brandonhaslegs** [comment]
@SouravInsights this isn't a logged in user. this is just a user who is added as a maintainer on a project.

So we should show the project(s) that user is a maintainer on on that user profile, whether they're logged in or not. essentially it'll just look like the claimed projects section on profiles.

**Comment by SouravInsights** [comment]
I see.. So the designs aren't yet ready right? @brandonhaslegs

**Comment by brandonhaslegs** [comment]
@SouravInsights not yet. also i just added a design label to make it clear it's not ready for dev yet! sorry for the confusion.

**Comment by SouravInsights** [comment]
No worries.. I just got too curious ha.. 😅

**Comment by brandonhaslegs** [comment]
This would require the new project card. I don't love repeating the text really…

<img width="597" alt="image" src="https://github.com/drips-network/app/assets/4406983/0006af15-db97-4e4b-9042-995c56a898ee">

Alternatively we could just add some headers. It's fine, just feels a bit clumsy since we'd have to have a header even if there was just one project. But this might be the way to go.
<img width="546" alt="image" src="https://github.com/drips-network/app/assets/4406983/1f6490ac-648a-4cfa-856c-c1c8e8d30922">

**Comment by efstajas** [comment]
what if you're both owner & maintainer of a project? project appears twice or only under "owner"? if the latter, not a big fan of the implication that owners are always also maintainers, which is ofc not true.

Generally given how it seems like the vast majority of projects have only one maintainer which is equal to the owner address OR split to some nondescript / ops Eth address that is not actually a "maintainer", not sure if we should actually do this tbh. For example, the Eth address that OpenCollective receives funds on would show up as a "maintainer" of 10+ projects if we do this, and there's no way to understand what's going on there. It might even look like something malicious is happening.

**Comment by brandonhaslegs** [comment]
You mean something like this? Feel like it looks kinda random

<img width="804" alt="Figma 2024-05-29 09 03 44" src="https://github.com/drips-network/app/assets/4406983/08a4fa68-42c5-4648-b995-837a176b3dc2">

**Comment by efstajas** [comment]
https://discord.com/channels/1096003917717983252/1246030633134850119/1246102485823918100
