### ISSUE TITLE
allow any user to start a Continuous Donation to a Drip List

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#983]
when you're the owner
![image](https://github.com/drips-network/app/assets/4406983/ece26117-7f37-49c4-98c4-08e2d2ba1e5e)

when you're not 
![image](https://github.com/drips-network/app/assets/4406983/b3330d2b-7b12-44a1-990e-89a1e2aba23b)

No reason for this

More context here

https://github.com/drips-network/app/assets/4406983/ba4fc9a9-9f38-46ec-8b1c-521381e26f69

This text needs to be updated when this is done.
<img width="503" alt="image" src="https://github.com/drips-network/app/assets/4406983/3ff1dd55-4a3a-46e9-a765-8492f2e5838c">

**Comment by ashiskumar-1999** [comment]
Hi@brandonhaslegs, can you provide more insight on how will it work?

**Comment by brandonhaslegs** [comment]
@ashiskumar-1999 I added more context above

**Comment by brandonhaslegs** [comment]
> Also, the given text should replace this one Donate instantly or add them to a Drip List. Right?

No it will just be a 3rd button. Like this:
<img width="455" alt="image" src="https://github.com/drips-network/app/assets/4406983/07c9d1b7-7fb9-4802-99ed-37141dbdb6ea">

**Comment by ashiskumar-1999** [comment]
Hi @brandonhaslegs, need a review on this PR. Review it once when you're available.

**Comment by brandonhaslegs** [comment]
best that @evvvritt or @efstajas reviews it.
