### ISSUE TITLE
Support Stream vs Continuous Donation

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#984]
Is there a reason to have two ways of refering to this?

<img width="692" alt="image" src="https://github.com/drips-network/app/assets/4406983/042ad66a-eec6-4e84-9735-101f766ca280">

<img width="308" alt="image" src="https://github.com/drips-network/app/assets/4406983/f1a3b2dd-91cf-4c36-a06d-edd81198b32e">

**Comment by nya-elimu** [comment]
What is the term used in the code? To avoid confusion, it might be best to use the same term everywhere, i.e. both in the code and in the UI.

**Comment by brandonhaslegs** [comment]
It should always be called Continuous Donation.
