### ISSUE TITLE
Drip list recipient truncation

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#989]
This list on the left side has 4 recipients, but it's getting truncated after the first two. Iit should just show all 4 recipients if there is space for 4.

<img width="1095" alt="image" src="https://github.com/drips-network/app/assets/4406983/09785e44-c32a-46bf-b03c-7f2738a6a646">

**Comment by evvvritt** [comment]
Not sure the logic but left has a description, maybe that's why it's truncated to fit? Are you suggesting no description's on card or?
